version: "3"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always

  server:
    container_name: graphql-prisma-nodejs
    environment:
      - PRISMA_ENDPOINT=$PRISMA_ENDPOINT
      - SECRET=$SECRET
      - ENDPOINT=$ENDPOINT
      - PORT=$PORT
      - EXPIRY=$EXPIRY
    restart: always
    build: ./server
    image: ${DOCKER_USERNAME}/graphql-prisma-nodejs
    ports:
      - "$PORT:$PORT"
